import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import env from '../config/env.config.js'
import modules from '../../registry/module.registry.js'
import { validateDependencies } from '../../registry/dependency-validator.js'

/** Walk up from this file until we find the directory containing package.json (the project root). */
function findProjectRoot(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url))
  while (!fs.existsSync(path.join(dir, 'package.json'))) {
    const parent = path.dirname(dir)
    if (parent === dir) throw new Error('Could not locate project root (package.json not found).')
    dir = parent
  }
  return dir
}

export interface AssembleResult {
  driver: string
  /** Modules whose fragment was included in the assembled schema. */
  includedModules: string[]
  /** Absolute path of the written schema file, or null for mongodb (no schema). */
  schemaPath: string | null
}

/**
 * Assemble prisma/schema.prisma from the driver-specific base block plus the
 * `db/*.prisma` fragment of every ENABLED module that ships one. Disabled
 * modules are omitted, so a subsequent `prisma db push` drops their tables.
 *
 * No-op for the mongodb driver (Mongoose has no schema migration).
 */
export function assembleSchema(): AssembleResult {
  validateDependencies(modules)

  if (env.DB_DRIVER === 'mongodb') {
    return { driver: 'mongodb', includedModules: [], schemaPath: null }
  }

  const root = findProjectRoot()
  const basePath = path.join(root, 'prisma', 'base', `${env.DB_DRIVER}.prisma`)
  if (!fs.existsSync(basePath)) {
    throw new Error(`Missing Prisma base block for driver "${env.DB_DRIVER}" at ${basePath}`)
  }

  const parts: string[] = [
    '// AUTO-GENERATED by src/core/database/schema-builder.ts — do not edit by hand.',
    `// Driver: ${env.DB_DRIVER}. Regenerate with: yarn db:sync`,
    '',
    fs.readFileSync(basePath, 'utf8').trim(),
  ]

  const includedModules: string[] = []
  for (const mod of modules) {
    if (!mod.enabled) continue
    const fragmentPath = path.join(root, 'src', 'modules', mod.name, 'db', `${mod.name}.prisma`)
    if (!fs.existsSync(fragmentPath)) continue
    parts.push('', `// ===== module: ${mod.name} =====`, fs.readFileSync(fragmentPath, 'utf8').trim())
    includedModules.push(mod.name)
  }

  const schemaPath = path.join(root, 'prisma', 'schema.prisma')
  fs.writeFileSync(schemaPath, parts.join('\n') + '\n')

  return { driver: env.DB_DRIVER, includedModules, schemaPath }
}
